sudo: required

services:
  - docker

before_install:
 - docker/build-docker.sh #presubmit

script:
 - docker run -it --rm -t zenlog_docker /bin/bash -c 'id;pwd;env;ls -l;"go/src/github.com/akawashiro/zenlog/scripts/presubmit.sh" && "go/src/github.com/akawashiro/zenlog/scripts/e2e-test.sh"' #presubmit
