# Sample ~/.zenlog.toml file.

ZENLOG_START_COMMAND = "exec /bin/bash -l"

# Log output directory.
ZENLOG_DIR = "/tmp/zenlog/"

# Prefix commands are ignored when command lines are parsed;
# for example "sudo cat" will considered to be a "cat" command.
ZENLOG_PREFIX_COMMANDS = "(?:builtin|command|time|sudo)"

# Always do not log output from these commands.
ZENLOG_ALWAYS_NO_LOG_COMMANDS = "(?:vim?|man|nano|pico|more|less|watch|emacs|ssh|h?top|nload|zenlog.*)"