ZENLOG_ALWAYS_NO_LOG_COMMANDS = "(?:fgrep|man)"

ZENLOG_USE_EXPERIMENTAL_COMMAND_PARSER = false

#ZENLOG_COMMAND_SPLITTER = '\s*(?:\;|\|\&|\|\||\||&&|\(|\)|{|})\s*'
#ZENLOG_COMMENT_SPLITTER = '(?:^|[\;\|\&\(\)\{\}]|\s+)\#\s*'